FROM python:3.11-slim

WORKDIR /code

# Install dependencies
COPY ./requirements.txt /code/requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r /code/requirements.txt

# Copy the app folder to the container
COPY ./app /code/app

# Expose both ports (8000 for API, 8501 for Streamlit)
EXPOSE 8000
EXPOSE 8501

# Run both process
RUN echo "#!/bin/bash\nuvicorn app.main1:app --host 0.0.0.0 --port 8000 &\nstreamlit run app/ui1.py --server.port 8501 --server.address 0.0.0.0" > start.sh
RUN chmod +x start.sh

CMD ["./start.sh"]