FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

# Copy all files
COPY . . 

# Expose both ports (8000 for API, 8501 for Streamlit)
EXPOSE 8000
EXPOSE 8501

# Run both process
RUN echo "#!/bin/bash\nuvicorn main1:app --host 0.0.0.0 --port 8000 &\nstreamlit run ui1.py --server.port 8501 --server.address 0.0.0.0" > start.sh
RUN chmod +x starts.sh

CMD ["./start.sh"]