name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          lfs: true  # Enable Git LFS support
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://irdazh:$HF_TOKEN@huggingface.co/spaces/irdazh/chatbot-ai main